import Head from "next/head";
import { useTheme } from "@/hooks/useTheme";
import tw, { styled } from "twin.macro";
import { Header } from "@/components/layout/Header/Header";

const Title = tw.h1`text-xl font-bold text-blue-500 mb-4`;
const Button = styled.button<{ isCold: boolean }>((props) => [
  tw`w-32 rounded h-10 bg-primary text-light shadow-lg bg-gradient-to-r`,
  props.isCold ? tw`from-cyan-500 to-blue-500` : tw`from-pink-500 to-orange-500`,
]);

export default function Home(params: any) {
  const { toggleTheme, theme } = useTheme();

  return (
    <section className="w-full h-full">
      <Head>
        <title>DevPad</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main className="bg-light flex flex-col items-center justify-center h-full">
        <Title>Hello DevPad World!</Title>
        <Button isCold={theme === "dark"} onClick={() => toggleTheme()}>
          Change Theme
        </Button>
      </main>
    </section>
  );
}
